export const TRAER_INVITADOS = 'TRAER_INVITADOS';
export const CARGANDO = 'CARGANDO_INVITADOS';
export const ERROR = 'ERROR_INVITADOS';
export const CHECKIN = 'CHECKIN_INVITADOS';
export const CHECKINQR = 'CHECKINQR_INVITADOS';