
export const TRAER_REGALOS = 'TRAER_REGALOS';
export const AGREGAR_REGALOS_EVENTO = 'AGREGAR_REGALOS_EVENTO';
export const VALUE_BANCO = 'VALUE_BANCO';
export const VALUE_CUIL = 'VALUE_CUIL';
export const VALUE_CBU = 'VALUE_CBU';
export const VALUE_PATH_IMG = 'VALUE_PATH_IMG';
export const VALUE_OBJETO = 'VALUE_OBJETO';
export const VALUE_SKU = 'VALUE_SKU';
export const VALUE_TIENDA = 'VALUE_TIENDA';
export const VALUE_LINK = 'VALUE_LINK';
export const VALUE_TIPO_DINERO_REGALO = 'VALUE_TIPO_DINERO_REGALO';
export const TIPO_REGALO = 'TIPO_REGALO';
export const CARGANDO = 'REGALOS_CARGANDO';
export const ERROR = 'REGALOS_ERROR';
export const LIMPIAR_FORM = 'LIMPIAR_FORM';
export const CARGANDO_GUARDAR = 'CARGANDO_GUARDAR';