export const FETCHED_SOCIAL_COMPANIES = 'FETCHED_SOCIAL_COMPANIES';

export const FETCHED_SOCIAL_EVENTS = 'FETCHED_SOCIAL_EVENTS';

export const FETCHED_SOCIAL_EVENT_HASHTAGS = 'FETCHED_SOCIAL_EVENT_HASHTAGS';

export const SET_SOCIAL_COMPANY = 'SET_SOCIAL_COMPANY';

export const SET_SOCIAL_EVENT = 'SET_SOCIAL_EVENT';