export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const SET_FULLSCREEN_STATE = 'SET_FULLSCREEN_STATE';

export const SET_TIMESTAMP_DIFF = 'SET_TIMESTAMP_DIFF';