export const TRAER_MENU_ETAPAS = 'TRAER_MENU_ETAPAS';
export const GUARDAR_MENU_ETAPA = 'GUARDAR_MENU_ETAPA';
export const VALUE_MENU_ETAPA_TITULO = 'VALUE_MENU_ETAPA_TITULO';
export const VALUE_MENU_ETAPA_DESCRIPCION = 'VALUE_MENU_ETAPA_DESCRIPCION';
export const ERROR = 'ERROR_MENU_ETAPA'
export const CARGANDO = 'CARGANDO_MENU_ETAPA'
export const CARGANDO_GUARDAR = 'CARGANDO_GUARDAR_MENU_ETAPA'
export const LIMPIAR_FORM = 'LIMPIAR_FORM_MENU_ETAPA'
    